package.path = package.path .. ';lua/?.lua'

local fs = require 'vim.fs'
local txt = fs.joinpath(fs.dirname(debug.getinfo(1).source:match("@?(.*)")), "test.txt")

-- luacheck: ignore 113
---@diagnostic disable: undefined-global
describe("test motion", function()
    local Motion = require "wordmotion".Motion
    local motion = Motion:from_path(txt)
    it("tests from path", function()
        assert.are.equal(#motion.lines, 3)
    end)
    it("tests utf8", function()
        local pos = motion:get_character(false, { 2, 0 })
        assert.are.equal(pos[1], 1)
        assert.are.equal(pos[2], 12)
        pos = motion:get_character(true, { 2, 15 })
        assert.are.equal(pos[1], 3)
        assert.are.equal(pos[2], 0)
        pos = motion:get_character(false, { 1, 0 })
        assert.are.equal(pos[1], 1)
        assert.are.equal(pos[2], 0)
        pos = motion:get_character(true, { 3, 24 })
        assert.are.equal(pos[1], 3)
        assert.are.equal(pos[2], 24)
    end)
end)

describe("test ^/$", function()
    local Motion = require "wordmotion.line".Motion
    local motion = Motion:from_path(txt)
    it("tests ^", function()
        local pos = motion:get_position(-1, true, { 2, 3 })
        assert.are.equal(pos[1], 2)
        assert.are.equal(pos[2], 0)
        pos = motion:get_position(-1, true, pos)
        assert.are.equal(pos[1], 2)
        assert.are.equal(pos[2], 0)
    end)
    it("tests $", function()
        local pos = motion:get_position(1, false, { 2, 3 })
        assert.are.equal(pos[1], 2)
        assert.are.equal(pos[2], 15)
        pos = motion:get_position(1, false, pos)
        assert.are.equal(pos[1], 2)
        assert.are.equal(pos[2], 15)
    end)
end)

describe("test h/l", function()
    local Motion = require "wordmotion.char".Motion
    local motion = Motion:from_path(txt)
    it("tests h", function()
        local pos = motion:get_position(-2, true, { 2, 6 })
        assert.are.equal(pos[1], 2)
        assert.are.equal(pos[2], 0)
    end)
    it("tests l", function()
        local pos = motion:get_position(3, true, { 2, 6 })
        assert.are.equal(pos[1], 2)
        assert.are.equal(pos[2], 15)
    end)
end)

describe("test B/E/W/gE", function()
    local Motion = require "wordmotion.word".Motion
    local motion = Motion:from_path(txt)
    it("tests B", function()
        local pos = motion:get_position(-1, true, { 1, 7 })
        assert.are.equal(pos[1], 1)
        assert.are.equal(pos[2], 0)
    end)
    it("tests W", function()
        local pos = motion:get_position(1, true, { 1, 7 })
        assert.are.equal(pos[1], 2)
        assert.are.equal(pos[2], 0)
    end)
end)
